---
title: "Reading assignments for 256"
---

# Evaluation

Each week those of you in 256 will read research papers and write a report describing the research and your evaluation of the work.
Each report should be 2-3 pages double-spaced.
See below for the list of papers and due dates.
You will submit your report on gradescope. 

The reports will be graded based on  <br>
• Correct identification of the research question
 <br>
• Accurate summary of the method used in the papers <br>
• Clear summary of the key results
 <br>
• Thoughtful overall evaluation of the paper (e.g., evaluating the significance, novelty, relevance of the contribution)

# Papers

| Reading | Link | Due date |
| --- | --- | --- |
| Bickel et al 1975 Science: Sex Bias in Graduate Admissions: Data from Berkeley  | [Link](https://www.jstor.org/stable/pdf/1739581.pdf) | 9/10/24 |
| Holland 1986 JASA Statistics and Causal Inference | [Link](https://www.cs.columbia.edu/~blei/fogm/2022F/readings/Holland1986.pdf) |9/17/24 |
| Miratrix 2013 JRSSB Adjusting treatment effect estimates by post-stratication in randomized experiments | [Link](https://rss.onlinelibrary.wiley.com/doi/full/10.1111/j.1467-9868.2012.01048.x) |9/24/24 |
| Lin 2013 AOAS: Agnostic notes on regression adjustments to experimental data: Reexamining Freedmans critique | [Link](https://projecteuclid.org/journals/annals-of-applied-statistics/volume-7/issue-1/Agnostic-notes-on-regression-adjustments-to-experimental-data--Reexamining/10.1214/12-AOAS583.full) | 10/01/24|
| Li, Ding and Rubin 2018 PNAS Asymptotic theory of rerandomization in treatment-control experiments  | [Link](https://www.pnas.org/doi/pdf/10.1073/pnas.1808191115) | 10/08/24|
| Rosenbaum and Rubin 1983 Biometrika: The central role of the propensity score in observational studies for causal effects | [Link](https://academic.oup.com/biomet/article/70/1/41/240879) | 10/15/24|
| Lunceford and Davidian 2004 SiM Stratification and weighting via the propensity score in estimation of causal treatment effects: a comparative study | [Link](https://onlinelibrary.wiley.com/doi/abs/10.1002/sim.1903?casa_token=rgWl1UEJxzQAAAAA%3AvcGTYNxR0YAZxnbFWLG4gicJmRhas5fgjoem6XxjOGvKXefH_AdCOjVibOyn2s-vaUXeG3S8lTcI9-U3) | 10/22/24 |
| Angrist Imbens and Rubin 1996 JASA Identification of causal effects using instrumental variables  | [Link](https://www.researchgate.net/profile/Joshua-Angrist/publication/38414432_Identification_of_Causal_Effects_Using_Instrumental_Variables_Rejoinder/links/00b4953344a9c27a25000000/Identification-of-Causal-Effects-Using-Instrumental-Variables-Rejoinder.pdf) | 10/29/24|
| Imbens 2014 StatSci Instrumental Variables: An Econometricians Perspective  | [Link](https://projecteuclid.org/journals/statistical-science/volume-29/issue-3/Instrumental-Variables-An-Econometricians-Perspective/10.1214/14-STS480.full) | 11/5/24|
| Ding and VanderWeele 2016 Epidemiology: Sensitivity Analysis Without Assumptions  | [Link](https://journals.lww.com/epidem/FullText/2016/05000/Sensitivity_Analysis_Without_Assumptions.11.aspx) |11/12/24 | 
| Pearl 1995 Biometrika Causal diagrams for empirical research  | [Link](https://www.jstor.org/stable/2337329) | 11/19/24|
| Frangakis and Rubin 2002 Biometrics Principal stratification in causal inference  | [Link](https://onlinelibrary.wiley.com/doi/abs/10.1111/j.0006-341X.2002.00021.x) |11/26/24 | 

