---
title: "Statistics 215b: Statistical Models: Theory and Application"
subtitle: "UC Berkeley, Spring 2026"
listing:
  # - id: schedule
  #   template: assets/schedule.ejs
  #  contents: schedule.yml
  - id: buttons
    template: assets/buttons.ejs
    contents: buttons.yml
---

::: {#buttons}
:::


::: {.callout-note title="Readings week 1"}
The reading for the first lecture is Chapter 1 of the textbook _A first course in causal inference_ by Peng Ding.
A preprint of the textbook is available on [arXiv](https://arxiv.org/pdf/2305.18793). The book is available 
in print [here](https://www.routledge.com/A-First-Course-in-Causal-Inference/Ding/p/book/9781032758626). 
 Add promotion code JSM24 for additional discount (good thru end of
September). 
:::

::: {.callout-note title="Readings week 2"}
The reading for the second lecture is Chapter 2 of _A first course in causal inference_.

The readings for the third lecture are 

1. Section 2.1 of the textbook _Causal inference: what if_ by 
James M. Robins and Miguel A. Hernán. Available [online](https://www.hsph.harvard.edu/miguel-hernan/causal-inference-book/).
2. Chapter 3 of _A first course in causal inference_.
:::

::: {.callout-note title="Readings week 3"}
The reading for the fourth lecture is Chapters 4-6 of _A first course in causal inference_.

The readings for the fifth lecture is Chapters 7-9 of _A first course in causal inference_.
:::

::: {.callout-note title="Readings week 4"}
The reading for the 9/17 lecture is

1. Chapter 3 of  _Causal inference: what if_.
2. Chapter 10 of _A first course in causal inference_.

The readings for the 9/19 lecture are

1. Section 2.4 of  _Causal inference: what if_.
2. Chapters 11-12 of _A first course in causal inference_.
:::

::: {.callout-note title="Homework 2 posted"}
Homework 2 for 156 is posted in the Homeworks tab.
:::

::: {.callout-note title="Homework 1 and Reading assignment 1 grades released"}
You can see your grade on Gradescope. Note that starting with homework 2, we will deduct points for failure to properly assign your gradescope pages to the corresponding problem AND for failure to submit code for coding problems.
:::

::: {.callout-note title="Readings week 5"}
The readings for the 9/24 lecture are

1. Chapter 12 of _A first course in causal inference_.
2. Chapter 13 of  _Causal inference: what if_.

The reading for the 9/26 lecture is

1.  Chapter 13 of _A first course in causal inference_.
:::

::: {.callout-note title="Readings week 6"}
The readings for the 10/01 lecture are

1. Chapter 4 of _Causal inference: what if_.
2. Chapter 15 of _A first course in causal inference_. 

The reading for the 10/03 lecture is

1.  Chapters 6 and 7 of _Causal inference: what if_.
:::

::: {.callout-note title="Homework 3 posted"}
Homework 3 for 156 is posted in the Homeworks tab.
:::


::: {.callout-note title="Readings week 7"}
The readings for the 10/08 lecture are

1. Chapter 16 of _Causal inference: what if_.
2. Chapter 16 of _A first course in causal inference_. 

The reading for the 10/10 lecture is

1.  Chapters 21-22 of _A first course in causal inference_.
:::

::: {.callout-note title="Readings week 8"}
There are no readings for the 10/15 lecture. Instead of a usual lecture, we will use this time for you to work on your group projects. 

The reading for the 10/17 lecture is

1.  Chapters 23 and 25 of _A first course in causal inference_.
:::

::: {.callout-note title="Homework 4 posted"}
Homework 4 for 156 is posted in the Homeworks tab.
:::

::: {.callout-note title="Guidelines posted for 256 Paper Presentation Videos"}
Guidelines for the 256 presentations on academic papers are available in the Video presentations tab.
:::

::: {.callout-note title="Readings week 9"}
The reading for the 10/22 lecture is

1. Chapter 20 of _A first course in causal inference_. 

The reading for the 10/24 lecture is

1.  Chapter 24 of _A first course in causal inference_.
:::

::: {.callout-note title="Readings week 10"}
There is no lecture on 10/29 as there is an in-class midterm.

The reading for the 10/31 lecture is

1.  Chapters 17-18 of _A first course in causal inference_.
:::

::: {.callout-note title="Readings week 11"}
The reading for the 11/5 lecture is

1. Chapter 19 of _A first course in causal inference_. 

The reading for the 11/7 lecture is

1.  Chapter 26 of _A first course in causal inference_.
:::

::: {.callout-note title="Homework 5 posted"}
Homework 5 for 156 is posted in the Homeworks tab.
:::

::: {.callout-note title="Readings week 12"}
The reading for the 11/12 lecture is

1. Chapter 23 of _Causal inference: what if_.
2. Chapter 27 of _A first course in causal inference_. 

There is no lecture on 11/14 due to [BSTARS](https://statistics.berkeley.edu/research/industry/berkeley-statistics-annual-research-symposium-bstars#:~:text=The%20Berkeley%20Statistics%20Annual%20Research,statistical%20problems%20encountered%20in%20industry.). Check out the event starting at 1 pm at Memorial Stadiu,/
:::


::: {.callout-note title="Homework 6 posted"}
Homework 6 for 156 is posted in the Homeworks tab.
:::

::: {.callout-note title="Readings week 13"}

The reading for the 11/19 lecture is

1.  Chapters 28 of _A first course in causal inference_.

The reading for the 11/21 lecture is

1.  Chapters 29 of _A first course in causal inference_.
:::

::: {.callout-note title="Project presentations schedule"}
256 Project Presentations will occur in class on 12/3.

156 Project Presentations will occur in class on 12/5.
:::
