---
title: "Syllabus"
---

# Navigation

- [About Stat 156/256](#about-stat-156256)
- [Syllabus for Stat 156](#syllabus-for-stat-156)
- [Syllabus for Stat 256](#syllabus-for-stat-256)

## About Stat 156/256

This course provides an introduction to causal inference using the potential outcomes framework and causal diagrams. We will cover topics such as randomized experiments, observational studies, instrumental variables, and mediation analysis. We will discuss applications of these methods to a variety of fields such as medicine and public policy. The course emphasizes both theory and data analysis. Lectures present concepts and methods, and lab sections focus on applications, derivations, and worked problems often using the statistical language R.

## Syllabus for Stat 156
- [Download PDF](./stat156-syllabus.pdf)

<embed
	src="./stat156-syllabus.pdf"
	type="application/pdf"
	width="100%"
	height="500px"
	title="Embedded PDF Viewer"
/>

## Syllabus for Stat 256
- [Download PDF](./stat256-syllabus.pdf)

<embed
	src="./stat256-syllabus.pdf"
	type="application/pdf"
	width="100%"
	height="500px"
	title="Embedded PDF Viewer"
/>